# Generated by Django 5.2.4 on 2025-08-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=200)),
                ('apellido_empleado', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('edad_empleado', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='contador_producto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='edad_empleado',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
