# Generated by Django 5.2.4 on 2025-08-13 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='email_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.categoria'),
        ),
    ]
