# Generated by Django 5.2.4 on 2025-08-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_alter_empleado_email_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='email_empleado',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
