# Generated by Django 5.2.4 on 2025-08-15 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_categoria_empleado_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.categoria'),
        ),
    ]
