# Generated by Django 5.2.4 on 2025-08-15 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_alter_empleado_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empleados.categoria'),
        ),
    ]
