# Generated by Django 5.2.4 on 2025-08-16 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0009_alter_empleado_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='email_empleado',
        ),
    ]
