# Generated by Django 5.2.4 on 2025-09-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0011_producto_fecha_producto_total_producto_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('pago movil', 'Pago Móvil'), ('transferencia', 'Transferencia')], default='efectivo', max_length=50),
        ),
    ]
