# Generated by Django 5.2.4 on 2025-09-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0012_alter_pedido_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='genero_empleado',
        ),
    ]
